apiVersion: safran.backstage.io/v1alpha1
kind: CloudProject
metadata:
  name: ftttt-namekkk
  description: a poc project for testing jm
  gitlab_group_id: 58866
  company_name: xxxx
spec:
  profile:
    displayName: fttt-namekkk
  creator: user:default/jmf02
  gitlab_group: jmfgrou/fttt-name
  onead_t1_group: xxxxxxxxxxxxx
  owner:
    name: user:default/jmf02
    email: jmf03@hotmail.com
  children: []
  members:
    - bouclier
    - EPEE
    - jmf02
    - jmf03
    - jmf05
    - smitth
